import type { AuthUser } from '../../types/auth';
import type { Panel } from './navigation';
import { LineVisualization } from '../../components/LineVisualization';
import { PageHeader } from '../../components/ui/PageHeader';
export type Overview={municipalities:number;lines:number;stations:number;buses:number;openTrips:number;visits:number}|null;
type Props={user:AuthUser;overview:Overview;panels:Panel[];onNavigate:(id:string)=>void;serviceAvailable:boolean;healthError:boolean};
export function DashboardHome({user,overview,panels,onNavigate,serviceAvailable,healthError}:Props) {
  const operator=user.role==='OPERADOR_ESTACION';
  const metrics=operator?[['Estaciones asignadas',user.stationIds.length,'Tu ámbito de operación'],['Registro de visitas','En orden','Cada parada conserva su evaluación'],['Demanda alta','≥ 150 %','Alerta de unidad adicional'],['Ocupación baja','< 25 %','Cinco minutos de espera adicional']]:[['Líneas habilitadas',overview?.lines,'Red en operación'],['Estaciones',overview?.stations,'Puntos de la red'],['Unidades',overview?.buses,'Buses activos'],['Recorridos abiertos',overview?.openTrips,'Seguimiento en curso']];
  return <section><PageHeader eyebrow="RESUMEN DE LA PLATAFORMA" title={`Hola, ${user.name.split(' ')[0]}`} description={operator?'Tu estación, sus recorridos y los registros del día, en un solo lugar.':'Una vista clara de la red, las unidades y la actividad de Transmetro.'} actions={<button className="button primary" onClick={()=>onNavigate(operator?'operations':'reports')}>{operator?'Registrar operación →':'Consultar reportes →'}</button>}/>
    {!serviceAvailable&&<div className="notice notice-warning" role="status">{healthError?'No se pudo verificar el servicio. Comprueba que el backend esté iniciado.':'Verificando la conexión con la API y MySQL…'}</div>}
    <div className="metric-grid">{metrics.map(([title,value,note])=><article className="metric-card" key={String(title)}><span>{title}</span><strong>{value??'—'}</strong><small>{note}</small></article>)}</div>
    <div className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><span className="eyebrow-text">{operator?'FLUJO DE TRABAJO':'RED OPERATIVA'}</span><h2>{operator?'Cada registro cuenta':'Líneas y conexiones'}</h2><p>{operator?'Información capturada por el operador y validada por la API.':'Orden de estaciones, distancias y puntos compartidos.'}</p></div></div>{operator?<ol className="workflow-list"><li><span>01</span><div><strong>Inicia el recorrido</strong><p>Selecciona la línea y una unidad disponible.</p></div></li><li><span>02</span><div><strong>Registra la siguiente estación</strong><p>Captura ocupación y demanda. El sistema evalúa ambas reglas.</p></div></li><li><span>03</span><div><strong>Actualiza tus conteos del día</strong><p>Solo aparecen medios habilitados en tus estaciones.</p></div></li></ol>:<LineVisualization/>}</article>
    <aside className="dashboard-side"><article className="panel"><span className="eyebrow-text">ACCESOS DIRECTOS</span><h2>Tu espacio de trabajo</h2><div className="quick-actions">{panels.filter(panel=>panel.id!=='home').map(panel=><button key={panel.id} onClick={()=>onNavigate(panel.id)}><span aria-hidden="true">{panel.icon}</span><strong>{panel.title}</strong><span>→</span></button>)}</div></article><article className="help-card"><span className="eyebrow-text">INFORMACIÓN CON HISTORIAL</span><h3>Decisiones con trazabilidad</h3><p>Las asignaciones, visitas y cambios de configuración conservan su responsable y fecha.</p><span className="badge badge-blue">{operator?'Acceso por estación':'Control por rol'}</span></article></aside></div>
  </section>;
}
