import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { apiRequest } from '../../api/client';
import { Badge, DataTable, textValue, type Column, type Row } from '../../components/ui/DataTable';
import { PageHeader, Notice } from '../../components/ui/PageHeader';
import { downloadCsv } from '../../lib/csv';
import { LineVisualization } from '../../components/LineVisualization';
import { relations, optionLabel } from '../catalog/relations';
const kinds=[['operations','Visitas y demanda'],['access-counts','Conteos por medio'],['fleet','Historial de flota'],['network','Mapa de líneas']];
const number=(value:unknown)=>Number(value??0).toLocaleString('es-GT',{maximumFractionDigits:2});
export function ReportsWorkspace() {
  const [kind,setKind]=useState('operations'),[filters,setFilters]=useState<Record<string,string>>({}),[result,setResult]=useState<Row>({}),[lookups,setLookups]=useState<Record<string,Row[]>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();Promise.all(['lineId','stationId','busId'].map(async key=>[key,(await apiRequest<{items:Row[]}>(relations[key].path,{signal:controller.signal})).items] as const)).then(entries=>setLookups(Object.fromEntries(entries))).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[]);
  useEffect(()=>{setFilters({});setResult({});setError('');if(kind==='network')return;const controller=new AbortController();setBusy(true);apiRequest<Row>(`/api/reports/${kind}`,{signal:controller.signal}).then(setResult).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[kind]);
  async function apply(event:FormEvent) {
    event.preventDefault();setError('');
    if(filters.from&&filters.to&&filters.from>filters.to){setError('La fecha inicial debe ser anterior a la final.');return;}
    setBusy(true);try{const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>Boolean(value)));setResult(await apiRequest<Row>(`/api/reports/${kind}?${query}`));}catch(e){setError(e instanceof Error?e.message:'No se pudo generar el reporte.');}finally{setBusy(false);}
  }
  const raw=(result.items??[]) as Row[];
  const rows=useMemo<Row[]>(()=>kind==='operations'?raw.map(row=>({fecha:row.fecha_hora,estacion:textValue(row.estacion),linea:textValue((row.recorrido as Row)?.linea),bus:textValue((row.recorrido as Row)?.bus),ocupacion:row.ocupacion,demanda:row.demanda,alerta:row.alerta_unidad_adicional,espera:row.espera_adicional_minutos,fuente:row.evaluationSource==='recorded'?'Capacidad registrada':'Capacidad actual (estimada)'})):kind==='fleet'?raw.flatMap(bus=>[...((bus.asignaciones_linea??[]) as Row[]).map(assignment=>({bus:bus.codigo,tipo:'Línea',destino:textValue(assignment.linea),inicio:assignment.fecha_inicio,fin:assignment.fecha_fin})),...((bus.asignaciones_parqueo??[]) as Row[]).map(assignment=>({bus:bus.codigo,tipo:'Parqueo',destino:textValue(assignment.parqueo),inicio:assignment.fecha_inicio,fin:assignment.fecha_fin}))]):raw,[kind,raw]);
  const columns:Column[]=kind==='operations'?[{key:'fecha',label:'Fecha',render:row=>new Date(String(row.fecha)).toLocaleString('es-GT')},{key:'linea',label:'Línea'},{key:'estacion',label:'Estación'},{key:'bus',label:'Bus'},{key:'ocupacion',label:'Ocupación'},{key:'demanda',label:'Demanda'},{key:'alerta',label:'Unidad adicional',render:row=>row.alerta?<span className="badge badge-warn">Requerida</span>:'No'},{key:'espera',label:'Espera (min)'},{key:'fuente',label:'Base de evaluación'}]:kind==='fleet'?[{key:'bus',label:'Bus'},{key:'tipo',label:'Asignación'},{key:'destino',label:'Destino'},{key:'inicio',label:'Desde',render:row=>new Date(String(row.inicio)).toLocaleString('es-GT')},{key:'fin',label:'Hasta',render:row=>row.fin?new Date(String(row.fin)).toLocaleString('es-GT'):<Badge value="EN_CURSO"/>}]:[{key:'station',label:'Estación'},{key:'medium',label:'Medio'},{key:'quantity',label:'Total de accesos'},{key:'records',label:'Registros'}];
  const summary=(result.summary??{}) as Row;
  const stats=kind==='operations'?[['Visitas',summary.visits],['Demanda total',summary.demandTotal],['Alertas de unidad',summary.extraUnitAlerts],['Visitas con espera',summary.additionalWaitVisits]]:kind==='access-counts'?[['Accesos registrados',result.totalQuantity],['Registros de conteo',result.totalRecords]]:[];
  return <section><PageHeader eyebrow="INFORMACIÓN PARA DECIDIR" title="Consultas y reportes" description="Filtra la información operativa y exporta los resultados que estás consultando." actions={kind!=='network'&&<button className="button secondary" disabled={busy||!rows.length} onClick={()=>downloadCsv(`transmetro-${kind}.csv`,columns.map(col=>col.label),rows.map(row=>columns.map(col=>textValue(row[col.key]))))}>↓ Exportar CSV</button>}/><div className="resource-tabs" role="tablist" aria-label="Reportes">{kinds.map(([key,title])=><button role="tab" aria-selected={kind===key} className={kind===key?'active':''} key={key} onClick={()=>setKind(key)}>{title}</button>)}</div><Notice error={error}/>
    {kind==='network'?<article className="panel"><LineVisualization/></article>:<><form className="report-filters panel" onSubmit={apply}>{kind!=='fleet'&&<><label>Desde<input type="date" value={filters.from??''} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Hasta<input type="date" min={filters.from} value={filters.to??''} onChange={e=>setFilters({...filters,to:e.target.value})}/></label></>}{(kind==='operations'?['lineId','stationId','busId']:kind==='fleet'?['lineId','busId']:['stationId']).map(key=><label key={key}>{relations[key].label}<select value={filters[key]??''} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">Todos</option>{lookups[key]?.map(row=><option key={String(row[relations[key].id])} value={String(row[relations[key].id])}>{optionLabel(row)}</option>)}</select></label>)}<button className="button primary" disabled={busy}>{busy?'Consultando…':'Aplicar filtros'}</button></form>{stats.length>0&&<div className="metric-grid">{stats.map(([title,value])=><article className="metric-card" key={String(title)}><span>{String(title)}</span><strong>{number(value)}</strong></article>)}</div>}{kind==='operations'&&Number(summary.estimatedVisits)>0&&<div className="notice notice-warning">{number(summary.estimatedVisits)} visitas del origen no tienen capacidad histórica registrada. Sus recomendaciones se estiman con la capacidad actual del bus.</div>}{Boolean(result.truncated)&&<div className="notice notice-warning">Los totales incluyen todos los registros coincidentes. La tabla y el CSV contienen las primeras {String(result.detailLimit)} visitas. Acota las fechas para exportar el detalle completo.</div>}<article className="panel"><DataTable rows={rows} columns={columns} loading={busy}/>{kind==='fleet'&&<p className="muted">Últimas 100 asignaciones de cada tipo por bus. Los filtros de línea y bus delimitan las unidades consultadas.</p>}</article></>}
  </section>;
}
